1 DIMENSIONAL SUBSETTING

In [ ]:
import numpy as np

a = np.array([1,2,'3',4,7])

print(a[2])

3


2 DIMENSIONAL SUBSETTING

In [ ]:
import numpy as np

a = np.array([[1,2,'3',4,7],[14,32,'30',40,22]])

print(a[1,1])

32


In [ ]:
import numpy as np

a = np.array([[1,3,4,5,5],[12,22,45,77,66]])

print(a[1,2])

45


In [ ]:
import numpy as np

a = np.array([[1,3,4,5,5],[12,22,45,77,66]])

print(a[1,3])

77


In [ ]:
import numpy as np

a = np.array([[1,3,4,5,5],[12,22,45,77,66]])

print(a[0,3])

5


3D SUBSETTING

In [ ]:
import numpy as np

a = np.array([[[1,3,'4',5,5],[12,22,'45',77,66]],[[12,33,'55',66,77],[1,22,'66',1007,99]]])

print(a[0,1,2])

45


1D SLICING

In [ ]:
import numpy as np

a = np.array([1,3,'4',5,5])

print(a[1:4])

['3' '4' '5']


In [ ]:
import numpy as np

a = np.array([1,3,4,5,5])

print(a[1:])

[3 4 5 5]


In [ ]:
import numpy as np

a = np.array([1,3,4,5,7])

print(a[:4])

[1 3 4 5]


2D SLICING

In [ ]:
import numpy as np

a = np.array([[1,3,4,5,5],[12,22,45,77,66]])

print(a.ndim)

#print(a)
print(a[0:2,2:5])     #0th and 1st row and 2nd 3rd 4th columns

print(a[ : ,1:3])     #0th and 1st row and 1st and 2nd columns

2
[[ 4  5  5]
 [45 77 66]]
[[ 3  4]
 [22 45]]


3D SLICING

In [ ]:
import numpy as np

a = np.array([[[1,3,4,5,5],[12,22,45,77,66]],[[1,14,25,17,88],[33,44,55,66,77]]])

print(a[: ,1,2:5])

[[45 77 66]
 [55 66 77]]


In [ ]:
import numpy as np

a = np.array([[[1,3,4,5,5],[12,22,45,77,66]],[[1,14,25,17,88],[33,44,55,66,77]]])

print(a[: , : ,1:4])

[[[ 3  4  5]
  [22 45 77]]

 [[14 25 17]
  [44 55 66]]]


BOOLEAN INDEXING

In [ ]:
import numpy as np

a = np.array([[[1,3,4,5,5],[12,22,45,77,66]],[[1,14,25,17,88],[33,44,55,66,77]]])

print(a)
print(a.ndim)
print(a.shape)

[[[ 1  3  4  5  5]
  [12 22 45 77 66]]

 [[ 1 14 25 17 88]
  [33 44 55 66 77]]]
3
(2, 2, 5)


In [ ]:
b = a>10

print(b)

[[[False False False False False]
  [ True  True  True  True  True]]

 [[False  True  True  True  True]
  [ True  True  True  True  True]]]


In [ ]:
b = a<10

print(b)

[[[ True  True  True  True  True]
  [False False False False False]]

 [[ True False False False False]
  [False False False False False]]]
